version: '3.9'
services:
  backend:
    tty: true
    build: ./backend
    env_file:
      - ./.env.user
    depends_on:
      db-init:
        condition: service_completed_successfully
  frontend:
    build: ./frontend-svelte
    depends_on:
      - backend
  db-init:
    build: ./db_init
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - ./.env.user
    environment:
      - ACCEPT_EULA=Y
  envoy:
    image: envoyproxy/envoy-alpine-dev
    ports:
      - "10000:10000"
      - "9901:9901"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    